### ISSUE TITLE
Python 3 Support

### ISSUE THREAD

**Issue by jseabold** [pyamg/pyamg#152]
Would be great if the swig wrappers and code were updated to run on Python 3.

**Comment by lukeolson** [comment]
Right.  One issue is that the new numpy.i is not compatible.  Scipy.sparse has changed to a manual wrapping.  I have a process for doing this automatically (https://github.com/lukeolson/crappy).  So hopefully (cross your fingers) this will be working soon without issue.  The other pieces all work through futurize and can be found in the branches but at the moment that's unusable without the C++ templates.

**Comment by jseabold** [comment]
Awesome thanks. I just gave it a shot and realized it wasn't going to be wholly trivial. Glad to hear it's on your radar.

**Comment by orkun-sim** [comment]
I have also tried but no success by far! I keep my fingers crossed so we will have Phyton 3 AMG - soon!

**Comment by bearnshaw** [comment]
First off, pyamg is a fantastic package, thanks @lukeolson.  Also glad to know the port to python 3 is on the radar.  I gave it a try myself and saw quickly I was out of my league.  Any update on the progress of this?

**Comment by lukeolson** [comment]
@bearnshaw thanks!   The plan is to have this at a working state in the next few weeks.  I have everything tested using futurize to support 2 and 3.  The hangup has been the c++ templates and those are almost ready.

**Comment by bearnshaw** [comment]
Great news @lukeolson, thanks again, looking forward to it.

**Comment by mfergie** [comment]
I share the above sentiments! Having Python 3 supported would be very useful for me. I'd be happy to help out if you can identify areas I could help with.

**Comment by bearnshaw** [comment]
@lukeolson any update on this?

**Comment by lukeolson** [comment]
Hey all.  I tagged a 3.0.0 version of pyamg here 031ee96e6efb5254cae01c33b034dda478e79d04

Master is now 3.0.0 with some pypi updates

A couple of notes:
- the SWIG interface has a complete overhaul
- I've tested with python 2.7, 3.4, and 3.5
- only tested with numpy 1.9/1.10 so let me know if you see issues

Right now I'm working on
- a larger matrix of CI tests for travis
- fixing the coverage testing so I can see where the unittests have 3.0 holes
- getting the wheel bug fixed with pypi, but this seems to be in pip itself: https://bitbucket.org/pypa/wheel/issues/146/wheel-building-fails-on-cpython-350b3

**Comment by lukeolson** [comment]
and it looks like I need to grab some fixes that @jedbrown found here https://github.com/pyamg/pyamg/compare/master...jedbrown:master

**Comment by mfergie** [comment]
Thank you very much @lukeolson, I've just installed and tested everything with Python 3.4 and it's all working correctly! Much appreciated.

**Comment by lukeolson** [comment]
this seems to be working for people so I'm closing it.  open an issue if you find specific problems.

**Comment by c-f-h** [comment]
Are these versions on the conda repository? The output of `conda info pyamg` shows that all versions depend on Python 2.x.
