### ISSUE TITLE
Question: gmres iteration history

### ISSUE THREAD

**Issue by arsenovicpt** [pyamg/pyamg#161]
Is there a simple way to get the iteration history of the solution vector x when calling gmres(A,b)? I get the converged solution but I would like the value of the solution vector during each iteration and store this in an array.

**Comment by jbschroder** [comment]
You can get the residual norm history by passing in an empty list for the
"residuals" parameter to GMRES.  But, there is no history of solution
vectors.  GMRES solves the problem in a reduced Krylov space, so there is
no way to get the history of solution vectors for "free".  If you wanted to
hack GMRES in PyAMG so that you collect and return the entire solution
vector history, then you could do that.  But, this is not a supported
option.

- Jacob

**Comment by lukeolson** [comment]
closing this.  @arsenovicpt if you need more input on hacking this, feel free to keep commenting in this thread.
