### ISSUE TITLE
ReadTheDocs

### ISSUE THREAD

**Issue by shoyer** [pyamg/pyamg#201]
I hooked up PyAMG to ReadTheDocs so I could view the documentation without building it locally:
http://pyamg.readthedocs.io

If any maintainers are interested in taking ownership, I would be very happy to pass it off to you. You can also setup web-hooks so the documentation is built automatically after every change.

**Comment by lukeolson** [comment]
Excellent!  I'd be happy to take over ... I'll start the process of linking to this on the main page...

**Comment by shoyer** [comment]
@lukeolson sure thing! Please let me know your username on readthedocs.org so I can add you.

**Comment by lukeolson** [comment]
its `lukeolson`

Thanks for pushing this along!

**Comment by shoyer** [comment]
Done! See https://readthedocs.org/projects/pyamg/ for the configuration page.

**Comment by lukeolson** [comment]
Great!  Thanks @shoyer

**Comment by lahwaacz** [comment]
The docs could use some attention regarding typography and [formatting](http://www.sphinx-doc.org/en/stable/rest.html), because things like missing punctuation marks at the end of sentences (see e.g. the [description of the `symmetry` parameter](http://pyamg.readthedocs.io/en/latest/_modules/pyamg/aggregation/adaptive.html#adaptive_sa_solver)) make the result pretty hard to read. In any case, it's definitely better than nothing - thanks @shoyer!

**Comment by lukeolson** [comment]
Thanks @lahwaacz .  I've started some fixes (1ff4d17a9bd4bab79bfc1f4be94363eefe97b0ed) and a new issue (#206).
