### ISSUE TITLE
correct strength documentation

### ISSUE THREAD

**Issue by lukeolson** [pyamg/pyamg#212]
`classical_strength_of_connection` is using an absolute value, but the docstring states that it does not.

**Comment by ben-s-southworth** [comment]
When we have time we should merge my classical branch into master. I
haven't bothered with a pull request because we haven't even looked at
the complexity one yet. But, I added options for both, added block SOC,
second-pass RS coarsening, distance two interpolation, and maybe a few
other things.

    https://github.com/ben-s-southworth/pyamg/tree/classical

Also note that in practice, for classical AMG anyways, the hard minimum
typically works better than the absolute value in my experience.
-ben

**Comment by lukeolson** [comment]
Yes.  we'll want to split these PRs into clear additions ... so we can verify/test more easily.  I can help with that.

**Comment by lukeolson** [comment]
@ben-s-southworth I added `_min` and `_abs` to classical and fixed some documentation.  Also added a `_min` test.  This seems to complete classical SOC: 85183d50e4dabe386af51adb8442134381301997

A few outstanding issues from your branch: blocks, classical (modified?) interpolation, distance 2 interp, etc. 

We should try to pack each of these separately for easy code review and testing.  Where to start?  Is distance two ready?

**Comment by ben-s-southworth** [comment]
classical and distance-two should both be good to go. Is there any good way to split them aside from manually copying out those pieces from my classical branch to a new branch?
