### ISSUE TITLE
Efficiently updating solvers for similar problems

### ISSUE THREAD

**Issue by shoyer** [pyamg/pyamg#219]
Can any of the solvers in PyAMG be efficiently updated for solving new matrices with similar structure/values?

I'm interested in the context of optimization problems, which involve solving many similar problems with small changes.

**Comment by ben-s-southworth** [comment]
Reusing parts of an AMG hierarchy for slightly modified problems is fairly
difficult. In particular, if you change a small part of your initial 
matrix, A,
then it will change the corresponding transfer operators R and P in relevant
rows/columns. Then, when you compute your first coarse-grid matrix,
Ac = R*A*P, this local change becomes a global change in the coarse-grid
operator, and everything from that point on has to be recomputed.

If the changes are quite small, you may be able to precondition A1 with
the AMG hierarchy for A0. Another idea is to use coarse-grid correction
for A0 coupled with a new relaxation based on A1, because relaxation
does not cost anything to set up. How well either of these would work is
highly problem dependent though.

**Comment by shoyer** [comment]
@ben-s-southworth thanks! I'm finding that reusing old preconditioners works OK for some of my problems.

**Comment by jbschroder** [comment]
Nice!  One thing to consider, is that when reusing, you could/should
replace solver.levels [0].A with the new matrix. In case you aren't already
doing this, I thought that I'd mention it.

Cheers,
Jacon
