### ISSUE TITLE
FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated

### ISSUE THREAD

**Issue by lukeolson** [pyamg/pyamg#229]
``` 
 /Users/travis/build/pyamg/pyamg/pyamg/gallery/stencil.py:110: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
    diag[s] = 0
```

**Comment by lukeolson** [comment]
fixed in a188d5b8c03337018d8fe4f8bb883a8decc95bb5

**Comment by kyoungseoun-chung** [comment]
> fixed in [a188d5b](https://github.com/pyamg/pyamg/commit/a188d5b8c03337018d8fe4f8bb883a8decc95bb5)

I saw that this issue is closed since it is fixed as lukeolson mentioned. 

However, when I check code v.4.0.0, this issue still persists. 

Is there any way to upgrade pyamg v.4.0.0 to pyamg v.4.1?

Nothing harmful but just a bit annoyed by a FutureWarning message.

Thank you in advance!

Best regards,
Kyoungseoun Chung

**Comment by lukeolson** [comment]
> Is there any way to upgrade pyamg v.4.0.0 to pyamg v.4.1?

I agree -- let's do this now.  I'll roll one out now.

Thanks for the nudge!

**Comment by lukeolson** [comment]
Ok, 4.1.0 is rolled out here: https://github.com/pyamg/pyamg/commit/7a74ef7f2a18b24d640ba8397822b8c2d2f8aa93

And it's in pypi:
https://pypi.org/project/pyamg/

I only have the source and a mac + Python 3.9 wheel up for now.  I'll try to automate the others.
